# Generated by Django 5.2.3 on 2025-06-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='skills.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='skills.skill'),
        ),
    ]
