# Generated by Django 5.2.3 on 2025-06-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_categort_user_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='categort',
            new_name='category',
        ),
    ]
