# Generated by Django 5.2.3 on 2025-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_alter_message_chat_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
